import { Mail, Save, ShieldCheck, Smartphone } from "lucide-react";
import { updateProfileAction } from "@/actions/settings";
import { ChangePasswordForm } from "@/components/auth/change-password-form";
import { PageHeader } from "@/components/dashboard/page-header";
import { SubmitButton } from "@/components/ui/submit-button";
import { requireRole } from "@/lib/auth";

export const metadata = { title: "Profilo famiglia" };
export default async function FamilyProfilePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await requireRole("PARENT"); const query = await searchParams;
  return <div className="page-container"><PageHeader eyebrow="Famiglia" title="Profilo e contatti" description="Le branche usano questi recapiti per gli avvisi." />{query.salvato && <div className="form-message form-message--success" style={{ marginBottom: 16 }}>Profilo aggiornato.</div>}<div className="detail-grid"><section className="panel"><form action={updateProfileAction}><div className="form-section"><div className="form-section__heading"><h2>Dati personali</h2><p>L'email resta quella usata durante la registrazione.</p></div><div className="form-grid form-grid--2"><label className="field"><span>Nome</span><input name="firstName" defaultValue={user.firstName} required /></label><label className="field"><span>Cognome</span><input name="lastName" defaultValue={user.lastName} required /></label><label className="field"><span>Telefono</span><input name="phone" type="tel" defaultValue={user.phone || ""} required /></label><label className="field"><span>Email</span><input value={user.email} disabled /></label></div></div><footer className="form-footer"><SubmitButton pendingText="Salvataggio..."><Save size={18} /> Salva contatti</SubmitButton></footer></form></section><aside className="dashboard-stack"><section className="panel"><header className="panel__header"><h2>Preferenze avvisi</h2></header><div className="panel__body"><div className="metric-line"><div className="metric-line__label"><Mail size={19} /><div><strong>Email</strong><span>{user.email}</span></div></div><strong>Attiva</strong></div><div className="metric-line"><div className="metric-line__label"><Smartphone size={19} /><div><strong>Telefono</strong><span>{user.phone || "Non impostato"}</span></div></div><strong>Solo contatto</strong></div></div></section><div className="notice notice--info"><ShieldCheck size={20} /><div><strong>Per ora gli avvisi automatici partono solo via email</strong><p>Il numero resta disponibile ai capi nell'elenco contatti.</p></div></div><ChangePasswordForm error={typeof query.password === "string" ? query.password : undefined} /></aside></div></div>;
}
