import Link from "next/link";
import { Check, ChevronRight, Edit3, Search, UserCheck, UsersRound, X } from "lucide-react";
import { approveChildAction, promoteBranchYearsAction, rejectChildAction } from "@/actions/children";
import { PageHeader } from "@/components/dashboard/page-header";
import { StatusPill } from "@/components/dashboard/status-pill";
import { requireAdminBranch } from "@/lib/branch";
import { prisma } from "@/lib/db";
import { formatDate, initials } from "@/lib/utils";

export const metadata = { title: "Ragazzi" };
export default async function AdminChildrenPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { branch } = await requireAdminBranch();
  const params = await searchParams;
  const query = typeof params.q === "string" ? params.q : "";
  const status = typeof params.stato === "string" && ["PENDING", "APPROVED", "REJECTED"].includes(params.stato) ? params.stato : undefined;
  const year = typeof params.anno === "string" ? Number(params.anno) : undefined;
  const children = await prisma.child.findMany({ where: { branchId: branch.id, ...(status ? { approvalStatus: status as "PENDING" | "APPROVED" | "REJECTED" } : {}), ...(year ? { schoolYear: year } : {}), ...(query ? { OR: [{ firstName: { contains: query, mode: "insensitive" } }, { lastName: { contains: query, mode: "insensitive" } }, { personCode: { contains: query, mode: "insensitive" } }] } : {}) }, include: { parents: { include: { user: true } }, _count: { select: { assignments: true } } }, orderBy: [{ approvalStatus: "desc" }, { schoolYear: "asc" }, { lastName: "asc" }] });
  return <div className="page-container"><PageHeader eyebrow={`${branch.group.name} / ${branch.name}`} title="Ragazzi" description={`${children.length} profili visualizzati`} actions={<form action={promoteBranchYearsAction.bind(null, branch.id)}><button className="button button--secondary" type="submit" title="Aumenta di uno l'anno di tutti i ragazzi fino al quarto"><ChevronRight size={18} /> Passaggio annuale</button></form>} />
    <form className="toolbar" method="get"><div className="toolbar__filters"><label className="search-box"><Search size={18} /><input className="search-input" name="q" defaultValue={query} placeholder="Cerca nome o codice" /></label><select className="filter-select" name="anno" defaultValue={year || ""}><option value="">Tutti gli anni</option>{[1,2,3,4,5].map((item) => <option key={item} value={item}>{item}° anno</option>)}</select><select className="filter-select" name="stato" defaultValue={status || ""}><option value="">Tutti gli stati</option><option value="PENDING">In attesa</option><option value="APPROVED">Approvati</option><option value="REJECTED">Rifiutati</option></select><button className="button button--secondary button--small" type="submit">Filtra</button></div></form>
    <section className="panel"><div className="panel__body--flush">{children.length ? <><table className="data-table"><thead><tr><th>Ragazzo</th><th>Anno</th><th>Nascita</th><th>Genitori e contatti</th><th>Richieste</th><th>Stato</th><th /></tr></thead><tbody>{children.map((child) => <tr key={child.id}><td><div className="table-person"><span className="avatar">{initials(child.firstName, child.lastName)}</span><span><strong>{child.firstName} {child.lastName}</strong><small>{child.personCode}</small></span></div></td><td>{child.schoolYear}°</td><td>{formatDate(child.birthDate)}</td><td>{child.parents.map(({ user }) => <span style={{ display: "block" }} key={user.id}>{user.firstName} {user.lastName} · {user.phone || user.email}</span>)}</td><td>{child._count.assignments}</td><td><StatusPill status={child.approvalStatus} /></td><td><div className="table-actions">{child.approvalStatus === "PENDING" && <><form action={approveChildAction.bind(null, child.id)}><button className="icon-button" type="submit" title="Approva"><Check size={17} /></button></form><form action={rejectChildAction.bind(null, child.id)}><input type="hidden" name="reason" value="Dati da verificare" /><button className="icon-button" type="submit" title="Rifiuta"><X size={17} /></button></form></>}<Link className="icon-button" href={`/admin/ragazzi/${child.id}`} title="Modifica"><Edit3 size={17} /></Link></div></td></tr>)}</tbody></table><div className="mobile-records">{children.map((child) => <article className="mobile-record" key={child.id}><div className="mobile-record__head"><div><strong>{child.firstName} {child.lastName}</strong><small>{child.personCode}</small></div><StatusPill status={child.approvalStatus} /></div><div className="mobile-record__meta"><span>Anno<strong>{child.schoolYear}°</strong></span><span>Nascita<strong>{formatDate(child.birthDate)}</strong></span><span>Genitore<strong>{child.parents[0] ? `${child.parents[0].user.firstName} ${child.parents[0].user.lastName}` : "-"}</strong></span><span>Telefono<strong>{child.parents[0]?.user.phone || "-"}</strong></span></div><div className="mobile-record__actions">{child.approvalStatus === "PENDING" && <form action={approveChildAction.bind(null, child.id)}><button className="button button--primary button--small" type="submit"><UserCheck size={16} /> Approva</button></form>}<Link className="button button--secondary button--small" href={`/admin/ragazzi/${child.id}`}><Edit3 size={16} /> Apri</Link></div></article>)}</div></> : <div className="empty-state"><UsersRound size={30} /><h3>Nessun ragazzo trovato</h3><p>Prova a cambiare i filtri oppure attendi una nuova richiesta di iscrizione.</p></div>}</div></section>
  </div>;
}
