import { Download, ExternalLink, FileText } from "lucide-react";
import { PageHeader } from "@/components/dashboard/page-header";
import { StatusPill } from "@/components/dashboard/status-pill";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { formatBytes, formatDateTime } from "@/lib/utils";

export const metadata = { title: "Documenti inviati" };
export default async function FamilyDocumentsPage() {
  const user = await requireRole("PARENT");
  const submissions = await prisma.submission.findMany({ where: { currentDriveFileId: { not: null }, assignment: { child: { parents: { some: { userId: user.id, approvalStatus: "APPROVED" } } } } }, include: { requestItem: true, assignment: { include: { child: true, request: true } } }, orderBy: { submittedAt: "desc" } });
  return <div className="page-container"><PageHeader eyebrow="Famiglia" title="Documenti inviati" description="I file vengono caricati dal Drive della branca solo quando li apri." /><section className="panel"><div className="panel__body--flush">{submissions.length ? <><table className="data-table"><thead><tr><th>Documento</th><th>Ragazzo</th><th>Richiesta</th><th>Caricato</th><th>Stato</th><th /></tr></thead><tbody>{submissions.map((submission) => <tr key={submission.id}><td><div className="table-person"><span className="avatar"><FileText size={17} /></span><span><strong>{submission.currentDriveFileName}</strong><small>{formatBytes(submission.currentSizeBytes)}</small></span></div></td><td>{submission.assignment.child.firstName} {submission.assignment.child.lastName}</td><td>{submission.assignment.request.title}</td><td>{formatDateTime(submission.submittedAt)}</td><td><StatusPill status={submission.status} /></td><td><div className="table-actions"><a className="icon-button" href={`/api/drive/files/${submission.currentDriveFileId}`} target="_blank" title="Apri"><ExternalLink size={17} /></a><a className="icon-button" href={`/api/drive/files/${submission.currentDriveFileId}?download=1`} title="Scarica"><Download size={17} /></a></div></td></tr>)}</tbody></table><div className="mobile-records">{submissions.map((submission) => <article className="mobile-record" key={submission.id}><div className="mobile-record__head"><div><strong>{submission.currentDriveFileName}</strong><small>{submission.assignment.child.firstName} · {formatBytes(submission.currentSizeBytes)}</small></div><StatusPill status={submission.status} /></div><div className="mobile-record__actions"><a className="button button--secondary button--small" href={`/api/drive/files/${submission.currentDriveFileId}`} target="_blank"><ExternalLink size={16} /> Apri</a><a className="button button--secondary button--small" href={`/api/drive/files/${submission.currentDriveFileId}?download=1`}><Download size={16} /> Scarica</a></div></article>)}</div></> : <div className="empty-state"><FileText size={30} /><h3>Nessun documento inviato</h3><p>I file caricati per le richieste compariranno qui.</p></div>}</div></section></div>;
}
