import Link from "next/link";
import { AlertTriangle, CheckCircle2, ExternalLink, Folder, FolderSync, Link2Off, Mail, Palette, Save, ShieldCheck } from "lucide-react";
import { copyBranchThemeAction, disconnectGoogleAction, migrateDriveDocumentsAction, updateBranchDetailsAction, updateBranchThemeAction, updateDriveFolderAction } from "@/actions/settings";
import { PageHeader } from "@/components/dashboard/page-header";
import { StatusPill } from "@/components/dashboard/status-pill";
import { ChangePasswordForm } from "@/components/auth/change-password-form";
import { FolderPicker } from "@/components/google/folder-picker";
import { SubmitButton } from "@/components/ui/submit-button";
import { requireAdminBranch } from "@/lib/branch";
import { prisma } from "@/lib/db";
import { formatBytes, formatDateTime } from "@/lib/utils";

export const metadata = { title: "Impostazioni branca" };
export default async function AdminSettingsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { branch } = await requireAdminBranch(); const query = await searchParams;
  const otherBranches = await prisma.branch.findMany({ where: { groupId: branch.groupId, id: { not: branch.id }, status: "ACTIVE" }, orderBy: { name: "asc" } });
  const transferableItems = await prisma.requestItem.findMany({
    where: { type: "FILE", request: { branchId: branch.id }, submissions: { some: { currentDriveFileId: { not: null } } } },
    include: { request: true, _count: { select: { submissions: { where: { currentDriveFileId: { not: null } } } } } },
    orderBy: [{ request: { createdAt: "desc" } }, { position: "asc" }],
    take: 60,
  });
  const googleConnection = branch.googleConnection;
  const connected = googleConnection?.status === "CONNECTED" && googleConnection.driveEnabled;
  return <div className="page-container"><PageHeader eyebrow={`${branch.group.name} / ${branch.name}`} title="Impostazioni" description="Drive, email, colori e limiti della branca." />
    {query.salvato && <div className="form-message form-message--success" style={{ marginBottom: 16 }}>Impostazioni salvate.</div>}
    {query.errore === "branca" && <div className="form-message form-message--error" style={{ marginBottom: 16 }}>Controlla nome e tipo della branca.</div>}
    {query.errore === "nome-duplicato" && <div className="form-message form-message--error" style={{ marginBottom: 16 }}>Nel gruppo esiste già una branca con questo nome.</div>}
    {query.google === "collegato" && <div className="notice notice--info"><CheckCircle2 size={20} /><div><strong>Account Google collegato</strong><p>Drive e, se autorizzata, Gmail sono pronti.</p></div></div>}
    {query.migrazione === "completata" && <div className="notice notice--info"><CheckCircle2 size={20} /><div><strong>Documenti trasferiti</strong><p>{query.copiati || "0"} file copiati nella cartella Drive attuale.</p></div></div>}
    {query.migrazione === "parziale" && <div className="notice notice--warning"><AlertTriangle size={20} /><div><strong>Trasferimento parziale</strong><p>{query.copiati || "0"} file copiati, {query.falliti || "0"} non riusciti.</p></div></div>}
    {query.migrazione === "seleziona" && <div className="notice notice--danger"><AlertTriangle size={20} /><div><strong>Nessun documento scelto</strong><p>Seleziona almeno un tipo documento da trasferire.</p></div></div>}
    {(query.google === "errore" || query.google === "cartella-non-accessibile") && <div className="notice notice--danger"><AlertTriangle size={20} /><div><strong>Collegamento Google non riuscito</strong><p>{googleConnection?.lastError || "Controlla autorizzazioni e cartella, poi riprova."}</p></div></div>}
    <section className="panel" style={{ marginBottom: 16 }}><header className="panel__header"><div><h2>Dati della branca</h2><p>Nome e tipologia visibili alle famiglie</p></div></header><form action={updateBranchDetailsAction}><div className="form-section"><div className="form-grid form-grid--2"><label className="field"><span>Nome branca</span><input name="name" defaultValue={branch.name} required /></label><label className="field"><span>Tipo di branca</span><select name="kind" defaultValue={branch.kind}><option value="LUPI">Lupi</option><option value="REPARTO">Reparto</option><option value="NOVIZIATO">Noviziato</option><option value="CLAN">Clan</option><option value="COMUNITA_CAPI">Comunità Capi</option><option value="ALTRO">Altro</option></select></label></div></div><footer className="form-footer"><SubmitButton pendingText="Salvataggio..."><Save size={18} /> Salva dati branca</SubmitButton></footer></form></section>
    <div className="dashboard-stack"><section className="panel"><header className="panel__header"><div><h2>Google Drive e Gmail</h2><p>I file restano nell'account della branca</p></div><StatusPill status={connected ? "CONNECTED" : googleConnection?.status || "DISCONNECTED"} /></header><div className="panel__body"><div className="detail-grid"><div><dl className="detail-list"><div><dt>Account</dt><dd>{googleConnection?.googleEmail || "Non collegato"}</dd></div><div><dt>Cartella</dt><dd>{googleConnection?.driveRootFolderName || "Non selezionata"}</dd></div><div><dt>Drive</dt><dd>{googleConnection?.driveEnabled ? "Autorizzato" : "Non autorizzato"}</dd></div><div><dt>Invio Gmail</dt><dd>{googleConnection?.gmailEnabled ? "Autorizzato" : "Non autorizzato"}</dd></div><div><dt>Ultimo controllo</dt><dd>{formatDateTime(googleConnection?.lastCheckedAt)}</dd></div></dl><div className="page-header__actions" style={{ marginTop: 16 }}>{connected ? <><FolderPicker branchId={branch.id} apiKey={process.env.NEXT_PUBLIC_GOOGLE_API_KEY} appId={process.env.NEXT_PUBLIC_GOOGLE_APP_ID} /><form action={disconnectGoogleAction.bind(null, branch.id)}><button className="button button--danger" type="submit"><Link2Off size={18} /> Scollega</button></form></> : <><Link className="button button--primary" href={`/api/google/connect?branchId=${branch.id}`}><Folder size={18} /> Collega Drive</Link><Link className="button button--secondary" href={`/api/google/connect?branchId=${branch.id}&gmail=1`}><Mail size={18} /> Collega Drive e Gmail</Link></>}</div></div><div><div className="notice notice--info"><ShieldCheck size={20} /><div><strong>Accesso alla cartella scelta</strong><p>GestioneLupi legge le sottocartelle gia presenti per non creare doppioni e salva i nuovi file nell'account della branca.</p></div></div>{connected && <form className="form-stack" action={updateDriveFolderAction}><label className="field"><span>Link o ID di un'altra cartella</span><input name="driveFolder" placeholder="https://drive.google.com/drive/folders/..." required /><small>La cartella deve essere accessibile dall'account Google collegato.</small></label><SubmitButton className="button button--secondary" pendingText="Verifica..."><ExternalLink size={17} /> Verifica e usa cartella</SubmitButton></form>}</div></div></div></section>
      {connected && transferableItems.length > 0 && <section className="panel"><header className="panel__header"><div><h2>Trasferisci documenti</h2><p>Copia solo alcuni documenti nella cartella Drive attuale</p></div><FolderSync size={19} /></header><form action={migrateDriveDocumentsAction}><div className="form-section"><div className="list">{transferableItems.map((item) => <label className="list-item" key={item.id}><input type="checkbox" name="requestItemId" value={item.id} /><span className="list-item__text"><strong>{item.driveFileName || item.title}</strong><small>{item.request.title} · {item._count.submissions} file disponibili</small></span></label>)}</div><label className="check-field" style={{ marginTop: 12 }}><input type="checkbox" name="deleteOld" /><span>Elimina le vecchie copie dopo il trasferimento</span></label></div><footer className="form-footer"><SubmitButton className="button button--secondary" pendingText="Trasferimento..."><FolderSync size={18} /> Trasferisci selezionati</SubmitButton></footer></form></section>}
      <section className="panel"><header className="panel__header"><div><h2>Aspetto della branca</h2><p>Colori applicati anche all'area famiglia</p></div><Palette size={19} /></header><form action={updateBranchThemeAction}><div className="form-section"><div className="form-grid form-grid--2"><label className="field"><span>Colore principale</span><input name="primaryColor" type="color" defaultValue={branch.primaryColor} /></label><label className="field"><span>Colore secondario</span><input name="secondaryColor" type="color" defaultValue={branch.secondaryColor} /></label><label className="field"><span>Colore accento</span><input name="accentColor" type="color" defaultValue={branch.accentColor} /></label><label className="field"><span>Logo URL <em>facoltativo</em></span><input name="logoUrl" type="url" defaultValue={branch.logoUrl || ""} /></label><label className="field"><span>Limite upload predefinito (MB)</span><input name="maxUploadMb" type="number" min="1" max="250" defaultValue={Math.round(branch.maxUploadBytes/1024/1024)} /><small>Attuale: {formatBytes(branch.maxUploadBytes)}</small></label></div></div><footer className="form-footer"><SubmitButton pendingText="Salvataggio..."><Save size={18} /> Salva aspetto</SubmitButton></footer></form></section>
      {otherBranches.length > 0 && <section className="panel"><header className="panel__header"><div><h2>Copia tema</h2><p>Riprendi colori e logo da un'altra branca del gruppo</p></div></header><form className="panel__body form-grid form-grid--2" action={copyBranchThemeAction}><label className="field"><span>Branca sorgente</span><select name="sourceBranchId">{otherBranches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><SubmitButton className="button button--secondary" pendingText="Copia...">Copia colori e logo</SubmitButton></form></section>}
      <ChangePasswordForm error={typeof query.password === "string" ? query.password : undefined} />
    </div></div>;
}
