import { Search, UsersRound } from "lucide-react";
import { PageHeader } from "@/components/dashboard/page-header";
import { StatusPill } from "@/components/dashboard/status-pill";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { formatDate, initials } from "@/lib/utils";

export const metadata = { title: "Utenti" };
export default async function SuperUsersPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireRole("SUPER_ADMIN"); const params = await searchParams; const query = typeof params.q === "string" ? params.q : "";
  const users = await prisma.user.findMany({ where: query ? { OR: [{ firstName: { contains: query, mode: "insensitive" } }, { lastName: { contains: query, mode: "insensitive" } }, { email: { contains: query, mode: "insensitive" } }] } : {}, include: { branchAdmins: { include: { branch: { include: { group: true } } } }, _count: { select: { children: true, sessions: true } } }, orderBy: { createdAt: "desc" }, take: 300 });
  return <div className="page-container"><PageHeader eyebrow="Super admin" title="Utenti" description={`${users.length} account visualizzati`} /><form className="toolbar"><label className="search-box"><Search size={18} /><input className="search-input" name="q" defaultValue={query} placeholder="Cerca nome o email" /></label></form><section className="panel"><div className="panel__body--flush"><table className="data-table"><thead><tr><th>Utente</th><th>Ruolo</th><th>Branca / figli</th><th>Registrato</th><th>Ultimo accesso</th><th>Stato</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><div className="table-person"><span className="avatar">{initials(user.firstName,user.lastName)}</span><span><strong>{user.firstName} {user.lastName}</strong><small>{user.email} · {user.phone || "nessun telefono"}</small></span></div></td><td>{user.role.replaceAll("_", " ")}</td><td>{user.branchAdmins[0] ? `${user.branchAdmins[0].branch.group.name} · ${user.branchAdmins[0].branch.name}` : `${user._count.children} figli`}</td><td>{formatDate(user.createdAt)}</td><td>{user.lastLoginAt ? formatDate(user.lastLoginAt) : "Mai"}</td><td><StatusPill status={user.status} /></td></tr>)}</tbody></table><div className="mobile-records">{users.map((user) => <article className="mobile-record" key={user.id}><div className="mobile-record__head"><div><strong>{user.firstName} {user.lastName}</strong><small>{user.email}</small></div><StatusPill status={user.status} /></div><div className="mobile-record__meta"><span>Ruolo<strong>{user.role.replaceAll("_"," ")}</strong></span><span>Registrato<strong>{formatDate(user.createdAt)}</strong></span></div></article>)}</div>{!users.length && <div className="empty-state"><UsersRound size={30} /><h3>Nessun utente trovato</h3><p>Prova con un'altra ricerca.</p></div>}</div></section></div>;
}
