import Link from "next/link";
import { ArrowLeft, Check, Mail, Save, UserCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { approveChildAction, approveParentLinkAction, updateChildAction } from "@/actions/children";
import { StatusPill } from "@/components/dashboard/status-pill";
import { SubmitButton } from "@/components/ui/submit-button";
import { requireAdminBranch } from "@/lib/branch";
import { prisma } from "@/lib/db";
import { formatDateTime } from "@/lib/utils";

export default async function ChildDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { branch } = await requireAdminBranch(); const { id } = await params; const query = await searchParams;
  const child = await prisma.child.findUnique({ where: { id }, include: { parents: { include: { user: true } }, branch: { include: { group: { include: { branches: { where: { status: "ACTIVE" }, orderBy: { name: "asc" } } } } } }, assignments: { include: { request: true }, orderBy: { createdAt: "desc" } } } });
  if (!child || child.branch.groupId !== branch.groupId) notFound();
  return <div className="page-container"><header className="page-header"><div className="page-header__text"><Link className="back-link" href="/admin/ragazzi"><ArrowLeft size={17} /> Torna ai ragazzi</Link><h1 style={{ marginTop: 14 }}>{child.firstName} {child.lastName}</h1><p>{child.branch.name} · {child.schoolYear}° anno · {child.personCode}</p></div><div className="page-header__actions"><StatusPill status={child.approvalStatus} />{child.approvalStatus !== "APPROVED" && <form action={approveChildAction.bind(null, child.id)}><button className="button button--primary" type="submit"><UserCheck size={18} /> Approva</button></form>}</div></header>
    {query.salvato && <div className="form-message form-message--success" style={{ marginBottom: 16 }}>Modifiche salvate.</div>}{query.errore && <div className="form-message form-message--error" style={{ marginBottom: 16 }}>Controlla i dati inseriti.</div>}
    <div className="detail-grid"><section className="panel"><form action={updateChildAction.bind(null, child.id)}><div className="form-section"><div className="form-section__heading"><h2>Dati anagrafici</h2><p>Gli admin possono correggere tutti i dati del ragazzo.</p></div><div className="form-grid form-grid--2"><label className="field"><span>Nome</span><input name="firstName" defaultValue={child.firstName} required /></label><label className="field"><span>Cognome</span><input name="lastName" defaultValue={child.lastName} required /></label><label className="field"><span>Codice persona</span><input name="personCode" defaultValue={child.personCode} required /></label><label className="field"><span>Data di nascita</span><input name="birthDate" type="date" defaultValue={child.birthDate.toISOString().slice(0,10)} required /></label><label className="field"><span>Sesso</span><select name="gender" defaultValue={child.gender}><option value="F">Femminile</option><option value="M">Maschile</option><option value="ALTRO">Altro / non specificato</option></select></label><label className="field"><span>Anno</span><select name="schoolYear" defaultValue={child.schoolYear}>{[1,2,3,4,5].map((year) => <option key={year} value={year}>{year}° anno</option>)}</select></label></div></div><div className="form-section"><div className="form-section__heading"><h2>Collocazione</h2><p>Puoi cambiare anno o spostare il ragazzo in un'altra branca del gruppo.</p></div><label className="field"><span>Branca</span><select name="branchId" defaultValue={child.branchId}>{child.branch.group.branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><div className="form-section"><label className="field"><span>Note interne</span><textarea name="notes" defaultValue={child.notes || ""} placeholder="Informazioni utili visibili solo agli admin" /></label></div><footer className="form-footer"><SubmitButton pendingText="Salvataggio..."><Save size={18} /> Salva modifiche</SubmitButton></footer></form></section>
      <aside className="dashboard-stack"><section className="panel"><header className="panel__header"><h2>Genitori collegati</h2></header><div className="panel__body">{child.parents.map((link) => <div className="metric-line" key={link.id}><div><strong>{link.user.firstName} {link.user.lastName}</strong><span style={{ display: "block", color: "var(--muted)", fontSize: ".75rem" }}>{link.user.email}<br />{link.user.phone || "Nessun telefono"}</span></div>{link.approvalStatus === "PENDING" ? <form action={approveParentLinkAction.bind(null, link.id)}><button className="icon-button" type="submit" title="Approva collegamento"><Check size={17} /></button></form> : <StatusPill status={link.approvalStatus} />}</div>)}</div></section><section className="panel"><header className="panel__header"><h2>Stato Drive</h2></header><div className="panel__body"><dl className="detail-list"><div><dt>Cartella</dt><dd>{child.driveFolderName || "Sara creata al primo upload"}</dd></div><div><dt>Approvato il</dt><dd>{formatDateTime(child.approvedAt)}</dd></div><div><dt>Richieste</dt><dd>{child.assignments.length}</dd></div></dl></div></section><a className="button button--secondary" href={`mailto:${child.parents.map((link) => link.user.email).join(",")}`}><Mail size={18} /> Scrivi ai genitori</a></aside>
    </div></div>;
}
