import Link from "next/link";
import { AlertTriangle, ArrowLeft, CalendarClock, CheckCircle2, Download, ExternalLink, FileText, Save, Upload } from "lucide-react";
import { notFound } from "next/navigation";
import { saveAnswerAction, uploadSubmissionAction } from "@/actions/submissions";
import { StatusPill } from "@/components/dashboard/status-pill";
import { SubmitButton } from "@/components/ui/submit-button";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { formatBytes, formatDate, formatDateTime } from "@/lib/utils";

export default async function FamilyRequestDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await requireRole("PARENT"); const { id } = await params; const query = await searchParams;
  const assignment = await prisma.requestAssignment.findUnique({ where: { id }, include: {
    child: { include: { branch: { include: { group: true } }, parents: true } },
    request: { include: { activity: true, items: { orderBy: { position: "asc" }, include: { template: true } } } },
    submissions: true,
  } });
  if (!assignment || !assignment.request.visibleToParents || assignment.request.status !== "PUBLISHED" || !assignment.child.parents.some((link) => link.userId === user.id && link.approvalStatus === "APPROVED")) notFound();
  const submissionByItem = new Map(assignment.submissions.map((submission) => [submission.requestItemId, submission]));
  return <div className="page-container"><header className="page-header"><div className="page-header__text"><Link className="back-link" href="/famiglia/richieste"><ArrowLeft size={17} /> Torna alle richieste</Link><h1 style={{ marginTop: 14 }}>{assignment.request.title}</h1><p>Per {assignment.child.firstName} {assignment.child.lastName} · {assignment.child.branch.group.name} / {assignment.child.branch.name}</p></div><div className="page-header__actions"><StatusPill status={assignment.status} /></div></header>
    {query.errore && <div className="notice notice--danger"><AlertTriangle size={20} /><div><strong>Non siamo riusciti a caricare il file</strong><p>{query.errore === "dimensione" ? "Il file supera il limite previsto." : query.errore === "formato" ? "Questo formato non e consentito per la richiesta." : query.errore === "drive" ? "Il Drive della branca non e disponibile. Avvisa i capi." : "Seleziona un file valido e riprova."}</p></div></div>}
    <div className="detail-grid"><section className="panel"><header className="panel__header"><div><h2>Elementi richiesti</h2><p>{assignment.request.items.length} elementi, quelli obbligatori sono indicati</p></div></header><div>{assignment.request.items.map((item) => { const submission = submissionByItem.get(item.id); return <section className="submission-item" key={item.id}><div className="submission-item__head"><div><h3>{item.title} {item.required && <span style={{ color: "var(--danger)" }}>*</span>}</h3><p>{item.description || (item.type === "FILE" ? "Carica il documento richiesto" : "Inserisci la tua risposta")}</p></div><StatusPill status={submission?.status || "MISSING"} /></div>
        {submission?.rejectionReason && <div className="notice notice--danger"><AlertTriangle size={18} /><div><strong>Da correggere</strong><p>{submission.rejectionReason}</p></div></div>}
        {item.template && <a className="button button--secondary button--small" href={`/api/drive/files/${item.template.driveFileId}?download=1`}><Download size={16} /> Scarica {item.template.fileName}</a>}
        {item.type === "FILE" && <div>{submission?.currentDriveFileId && <div className="metric-line"><div className="metric-line__label"><FileText size={19} /><div><strong>{submission.currentDriveFileName}</strong><span>{formatBytes(submission.currentSizeBytes)} · caricato {formatDateTime(submission.submittedAt)}</span></div></div><a className="button button--secondary button--small" href={`/api/drive/files/${submission.currentDriveFileId}`} target="_blank"><ExternalLink size={16} /> Apri</a></div>}{submission?.pendingDriveFileId && <div className="notice notice--info"><Upload size={18} /><div><strong>Nuova versione in attesa</strong><p>L'admin deve approvare la sostituzione del documento precedente.</p></div></div>}<form action={uploadSubmissionAction.bind(null, assignment.id, item.id)} className="file-drop"><input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.heic,.doc,.docx,.xlsx" required /><SubmitButton className="button button--primary button--small" pendingText="Caricamento..."><Upload size={16} /> {submission?.currentDriveFileId ? "Sostituisci" : "Carica"}</SubmitButton></form></div>}
        {item.type === "TEXT" && <form action={saveAnswerAction.bind(null, assignment.id, item.id)} className="form-stack"><label className="field"><span>Risposta</span><textarea name="value" defaultValue={submission?.textValue || ""} required={item.required} /></label><SubmitButton className="button button--primary button--small" pendingText="Salvataggio..."><Save size={16} /> Salva risposta</SubmitButton></form>}
        {item.type === "BOOLEAN" && <form action={saveAnswerAction.bind(null, assignment.id, item.id)} className="form-stack"><div className="segmented"><label><input type="radio" name="value" value="true" defaultChecked={submission?.booleanValue === true} required />Si</label><label><input type="radio" name="value" value="false" defaultChecked={submission?.booleanValue === false} required />No</label></div><SubmitButton className="button button--primary button--small" pendingText="Salvataggio..."><Save size={16} /> Salva conferma</SubmitButton></form>}
      </section>; })}</div></section>
      <aside className="dashboard-stack"><section className="panel"><header className="panel__header"><h2>Riepilogo</h2></header><div className="panel__body"><dl className="detail-list"><div><dt>Stato</dt><dd><StatusPill status={assignment.status} /></dd></div><div><dt>Scadenza</dt><dd>{assignment.request.dueDate ? formatDate(assignment.request.dueDate) : "Nessuna"}</dd></div><div><dt>Attivita</dt><dd>{assignment.request.activity?.title || "Nessuna"}</dd></div><div><dt>Revisione</dt><dd>{assignment.request.requiresApproval ? "Richiesta" : "Automatica"}</dd></div></dl></div></section>{assignment.request.description && <section className="panel"><header className="panel__header"><h2>Indicazioni</h2></header><div className="panel__body"><p style={{ margin: 0, whiteSpace: "pre-wrap" }}>{assignment.request.description}</p></div></section>}{["APPROVED","COMPLETED"].includes(assignment.status) && <div className="notice notice--info"><CheckCircle2 size={20} /><div><strong>Richiesta completata</strong><p>I documenti restano disponibili finche sono presenti nel Drive della branca.</p></div></div>}<div className="notice notice--info"><CalendarClock size={20} /><div><strong>I file non restano sul sito</strong><p>Vengono inviati direttamente alla cartella Drive della branca.</p></div></div></aside>
    </div></div>;
}
