import { Building2, Check, Link2, Pause, UsersRound } from "lucide-react";
import { approveBranchAction, suspendBranchAction } from "@/actions/super-admin";
import { PageHeader } from "@/components/dashboard/page-header";
import { StatusPill } from "@/components/dashboard/status-pill";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { formatDate } from "@/lib/utils";

export const metadata = { title: "Gruppi e branche" };
export default async function SuperBranchesPage() {
  await requireRole("SUPER_ADMIN");
  const groups = await prisma.scoutGroup.findMany({ include: { branches: { include: { googleConnection: true, admins: { include: { user: true } }, _count: { select: { children: true, requests: true } } }, orderBy: { name: "asc" } } }, orderBy: { name: "asc" } });
  return <div className="page-container"><PageHeader eyebrow="Super admin" title="Gruppi e branche" description="Approvazioni, account, collegamenti e stato operativo." />
    <div className="dashboard-stack">{groups.map((group) => <section className="panel" key={group.id}><header className="panel__header"><div><h2>{group.name}</h2><p>{group.city || "Citta non indicata"} · {group.branches.length} branche</p></div><Building2 size={20} /></header><div className="panel__body--flush"><table className="data-table"><thead><tr><th>Branca</th><th>Account</th><th>Membri</th><th>Richieste</th><th>Drive / Gmail</th><th>Creata</th><th>Stato</th><th /></tr></thead><tbody>{group.branches.map((branch) => <tr key={branch.id}><td><strong>{branch.name}</strong><br /><small>{branch.kind.replaceAll("_", " ")}</small></td><td>{branch.email}</td><td>{branch._count.children}</td><td>{branch._count.requests}</td><td><span title="Drive"><Link2 size={15} color={branch.googleConnection?.driveEnabled ? "var(--success)" : "var(--subtle)"} /></span> <span title="Gmail"><Link2 size={15} color={branch.googleConnection?.gmailEnabled ? "var(--success)" : "var(--subtle)"} /></span></td><td>{formatDate(branch.createdAt)}</td><td><StatusPill status={branch.status} /></td><td><div className="table-actions">{branch.status === "PENDING" && <form action={approveBranchAction.bind(null, branch.id)}><button className="icon-button" title="Approva" type="submit"><Check size={17} /></button></form>}{branch.status === "ACTIVE" && <form action={suspendBranchAction.bind(null, branch.id)}><button className="icon-button" title="Sospendi" type="submit"><Pause size={17} /></button></form>}</div></td></tr>)}</tbody></table><div className="mobile-records">{group.branches.map((branch) => <article className="mobile-record" key={branch.id}><div className="mobile-record__head"><div><strong>{branch.name}</strong><small>{branch.email}</small></div><StatusPill status={branch.status} /></div><div className="mobile-record__meta"><span>Membri<strong>{branch._count.children}</strong></span><span>Richieste<strong>{branch._count.requests}</strong></span><span>Drive<strong>{branch.googleConnection?.driveEnabled ? "Collegato" : "No"}</strong></span><span>Gmail<strong>{branch.googleConnection?.gmailEnabled ? "Collegato" : "No"}</strong></span></div>{branch.status === "PENDING" && <form action={approveBranchAction.bind(null, branch.id)}><button className="button button--primary button--small" type="submit"><Check size={16} /> Approva</button></form>}</article>)}</div></div></section>)}</div>{!groups.length && <div className="empty-state"><UsersRound size={30} /><h3>Nessun gruppo</h3><p>Le registrazioni delle branche creeranno qui i gruppi necessari.</p></div>}
  </div>;
}
