import Link from "next/link";
import { ArrowLeft, Save } from "lucide-react";
import { notFound } from "next/navigation";
import { updateRequestAction } from "@/actions/requests";
import { SubmitButton } from "@/components/ui/submit-button";
import { requireAdminBranch } from "@/lib/branch";
import { prisma } from "@/lib/db";

export default async function EditRequestPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { branch } = await requireAdminBranch(); const { id } = await params; const query = await searchParams;
  const [request, activities] = await Promise.all([
    prisma.documentRequest.findUnique({ where: { id }, include: { items: { orderBy: { position: "asc" } } } }),
    prisma.activity.findMany({ where: { branchId: branch.id, status: { in: ["OPEN","DRAFT"] } }, orderBy: { title: "asc" } }),
  ]);
  if (!request || request.branchId !== branch.id) notFound();
  return <div className="page-container"><header className="page-header"><div className="page-header__text"><Link className="back-link" href={`/admin/richieste/${request.id}`}><ArrowLeft size={17} /> Torna alla richiesta</Link><h1 style={{ marginTop: 14 }}>Modifica richiesta</h1><p>{request.status === "DRAFT" ? "La bozza non e ancora visibile alle famiglie." : "Le assegnazioni gia pubblicate restano collegate ai destinatari originari."}</p></div></header>{query.errore && <div className="form-message form-message--error" style={{ marginBottom: 16 }}>Controlla i dati inseriti.</div>}<section className="panel"><form action={updateRequestAction.bind(null, request.id)}><div className="form-section"><div className="form-section__heading"><h2>Informazioni</h2></div><div className="form-grid"><label className="field"><span>Titolo</span><input name="title" defaultValue={request.title} required /></label><label className="field"><span>Descrizione</span><textarea name="description" defaultValue={request.description || ""} /></label><div className="form-grid form-grid--2"><label className="field"><span>Attivita</span><select name="activityId" defaultValue={request.activityId || ""}><option value="">Nessuna</option>{activities.map((activity) => <option key={activity.id} value={activity.id}>{activity.title}</option>)}</select></label><label className="field"><span>Scadenza</span><input name="dueDate" type="date" defaultValue={request.dueDate?.toISOString().slice(0,10) || ""} /></label></div></div></div>
    <div className="form-section"><div className="form-section__heading"><h2>Elementi richiesti</h2><p>Puoi correggere testi, nomi Drive e limiti anche dopo la pubblicazione.</p></div><div className="builder-items">{request.items.map((item, index) => <div className="builder-item" key={item.id}><span className="builder-item__handle"><strong>{index+1}</strong></span><div className="builder-item__fields"><div className="form-grid form-grid--2"><label className="field"><span>Etichetta</span><input name={`itemTitle-${item.id}`} defaultValue={item.title} required /></label><label className="field"><span>Tipo</span><input value={item.type === "FILE" ? "Caricamento file" : item.type === "TEXT" ? "Risposta testuale" : "Conferma si/no"} disabled /></label></div><label className="field"><span>Istruzioni</span><input name={`itemDescription-${item.id}`} defaultValue={item.description || ""} /></label>{item.type === "FILE" && <div className="form-grid form-grid--2"><label className="field"><span>Nome su Drive</span><input name={`driveFileName-${item.id}`} defaultValue={item.driveFileName || item.title} /></label><label className="field"><span>Limite MB</span><input name={`maxFileSizeMb-${item.id}`} type="number" min="1" max="250" defaultValue={item.maxFileSize ? Math.round(item.maxFileSize/1024/1024) : Math.round(branch.maxUploadBytes/1024/1024)} /></label></div>}<label className="check-field"><input type="checkbox" name={`required-${item.id}`} defaultChecked={item.required} /><span>Elemento obbligatorio</span></label></div></div>)}</div></div>
    <div className="form-section"><div className="settings-checks"><label className="check-setting"><input type="checkbox" name="visibleToParents" defaultChecked={request.visibleToParents} /><span><strong>Visibile ai genitori</strong><small>Mostra o nasconde la richiesta</small></span></label><label className="check-setting"><input type="checkbox" name="requiresApproval" defaultChecked={request.requiresApproval} /><span><strong>Revisione admin</strong><small>Approva le consegne manualmente</small></span></label><label className="check-setting"><input type="checkbox" name="emailOnPublish" defaultChecked={request.emailOnPublish} /><span><strong>Email alla pubblicazione</strong><small>Disponibile per le bozze</small></span></label><label className="check-setting"><input type="checkbox" name="reminderEnabled" defaultChecked={request.reminderEnabled} /><span><strong>Promemoria</strong><small>Contatta i mancanti</small></span></label></div></div><footer className="form-footer"><Link className="button button--secondary" href={`/admin/richieste/${request.id}`}>Annulla</Link><SubmitButton pendingText="Salvataggio..."><Save size={18} /> Salva modifiche</SubmitButton></footer></form></section></div>;
}
