import Link from "next/link";
import { AlertTriangle, Building2, CheckCircle2, Database, FileWarning, History, Mail, UsersRound } from "lucide-react";
import { approveBranchAction } from "@/actions/super-admin";
import { PageHeader } from "@/components/dashboard/page-header";
import { StatCard } from "@/components/dashboard/stat-card";
import { StatusPill } from "@/components/dashboard/status-pill";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { timeAgo } from "@/lib/utils";

export const metadata = { title: "Controllo globale" };
export default async function SuperDashboardPage() {
  await requireRole("SUPER_ADMIN");
  const [groups, branches, users, missing, pendingBranches, errors, logs] = await Promise.all([
    prisma.scoutGroup.count(), prisma.branch.count({ where: { status: "ACTIVE" } }), prisma.user.count({ where: { status: "ACTIVE" } }), prisma.requestAssignment.count({ where: { status: { in: ["MISSING", "NEEDS_CHANGES"] }, request: { status: "PUBLISHED" } } }),
    prisma.branch.findMany({ where: { status: "PENDING" }, include: { group: true, admins: { include: { user: true } }, googleConnection: true }, orderBy: { createdAt: "asc" } }),
    prisma.googleConnection.count({ where: { status: "ERROR" } }), prisma.auditLog.findMany({ include: { branch: { include: { group: true } }, actor: true }, orderBy: { createdAt: "desc" }, take: 8 }),
  ]);
  return <div className="page-container"><PageHeader eyebrow="Controllo globale" title="Panoramica GestioneLupi" description="Stato del servizio, approvazioni e problemi da risolvere." actions={<Link className="button button--secondary" href="/super/log"><History size={18} /> Apri log completo</Link>} />
    <div className="stats-grid"><StatCard label="Gruppi" value={groups} hint={`${branches} branche attive`} icon={Building2} /><StatCard label="Utenti attivi" value={users} hint="tutti i ruoli" icon={UsersRound} /><StatCard label="Consegne aperte" value={missing} hint="mancanti o da correggere" icon={FileWarning} tone={missing ? "warning" : "success"} /><StatCard label="Errori integrazioni" value={errors} hint="Drive o Gmail" icon={AlertTriangle} tone={errors ? "danger" : "success"} /></div>
    <div className="dashboard-grid"><div className="dashboard-stack"><section className="panel"><header className="panel__header"><div><h2>Branche da approvare</h2><p>{pendingBranches.length} richieste in attesa</p></div><Link className="text-link" href="/super/branche">Gestisci tutte</Link></header><div className="panel__body--flush">{pendingBranches.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Branca</th><th>Account</th><th>Drive</th><th /></tr></thead><tbody>{pendingBranches.map((branch) => <tr key={branch.id}><td><strong>{branch.group.name} · {branch.name}</strong></td><td>{branch.email}</td><td><StatusPill status={branch.googleConnection?.driveRootFolderId ? "PENDING" : "DISCONNECTED"} label={branch.googleConnection?.driveRootFolderId ? "Indicata" : "Da collegare"} /></td><td><form action={approveBranchAction.bind(null, branch.id)}><button className="button button--primary button--small" type="submit"><CheckCircle2 size={16} /> Approva</button></form></td></tr>)}</tbody></table><div className="mobile-records">{pendingBranches.map((branch) => <div className="mobile-record" key={branch.id}><div className="mobile-record__head"><div><strong>{branch.group.name} · {branch.name}</strong><small>{branch.email}</small></div><StatusPill status="PENDING" /></div><div className="mobile-record__actions"><form action={approveBranchAction.bind(null, branch.id)}><button className="button button--primary button--small" type="submit">Approva</button></form></div></div>)}</div></div> : <div className="empty-state"><CheckCircle2 size={30} /><h3>Nessuna approvazione in attesa</h3><p>Le nuove branche compariranno qui.</p></div>}</div></section>
      <section className="panel"><header className="panel__header"><div><h2>Ultime operazioni</h2><p>Da tutti i gruppi</p></div><Link className="text-link" href="/super/log">Vedi log</Link></header><div className="list">{logs.map((log) => <div className="list-item" key={log.id}><span className="list-item__icon"><Database size={18} /></span><span className="list-item__text"><strong>{log.summary}</strong><small>{log.branch ? `${log.branch.group.name} · ${log.branch.name}` : "Sistema"}</small></span><span className="list-item__meta">{timeAgo(log.createdAt)}</span></div>)}</div></section></div>
      <aside className="dashboard-stack"><section className="panel"><header className="panel__header"><h2>Stato servizio</h2></header><div className="panel__body"><div className="metric-line"><div className="metric-line__label"><Database size={19} /><div><strong>Database</strong><span>PostgreSQL</span></div></div><StatusPill status="CONNECTED" /></div><div className="metric-line"><div className="metric-line__label"><Building2 size={19} /><div><strong>Drive collegati</strong><span>Per branca</span></div></div><strong>{await prisma.googleConnection.count({ where: { driveEnabled: true } })}/{branches}</strong></div><div className="metric-line"><div className="metric-line__label"><Mail size={19} /><div><strong>Gmail collegati</strong><span>Invio di branca</span></div></div><strong>{await prisma.googleConnection.count({ where: { gmailEnabled: true } })}/{branches}</strong></div></div></section></aside></div>
  </div>;
}
